import { Layout } from "@/components/layout";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { useQrAttendanceHistory, useMyQrCard } from "@/hooks/use-qr-attendance";
import { useToast } from "@/hooks/use-toast";
import { copyToClipboard, buildQrImageUrl } from "@/lib/qr";
import { formatDate, getErrorMessage } from "@/lib/utils";
import { api } from "@shared/routes";
import { Copy, Loader2, QrCode, ShieldCheck } from "lucide-react";
import { z } from "zod";

type QrHistoryEvent = NonNullable<z.infer<(typeof api.qrAttendance.history.responses)[200]>["data"]>["events"][number];

export default function StudentQrCard() {
  const { toast } = useToast();
  const { data, isLoading } = useMyQrCard();
  const { data: history = [] } = useQrAttendanceHistory();

  const handleCopy = async () => {
    if (!data?.token) return;
    try {
      await copyToClipboard(data.token);
      toast({ title: "QR token copied", description: "A manual fallback token has been copied to your clipboard." });
    } catch (error) {
      toast({ title: "Unable to copy token", description: getErrorMessage(error), variant: "destructive" });
    }
  };

  return (
    <Layout>
      <div className="space-y-6 pb-8">
        <div>
          <h1 className="text-3xl font-display font-bold">My QR Card</h1>
          <p className="mt-1 text-muted-foreground">Present this QR card for fast attendance check-in. Your manual token is also available as a fallback.</p>
        </div>

        <div className="grid gap-6 xl:grid-cols-[1fr_0.95fr]">
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2"><QrCode className="h-5 w-5" /> Student Attendance Pass</CardTitle>
              <CardDescription>This QR identity is auto-issued on first access and can be regenerated by an administrator if needed.</CardDescription>
            </CardHeader>
            <CardContent>
              {isLoading || !data ? (
                <div className="flex min-h-[360px] items-center justify-center"><Loader2 className="h-6 w-6 animate-spin text-violet-600" /></div>
              ) : (
                <div className="grid gap-6 lg:grid-cols-[320px_1fr]">
                  <div className="rounded-[1.5rem] border bg-slate-50 p-5 text-center">
                    <img src={buildQrImageUrl(data.token)} alt="Student QR card" className="mx-auto aspect-square w-full max-w-[280px] rounded-2xl border bg-white p-3" />
                    <div className="mt-4 flex items-center justify-center gap-2">
                      <Badge variant={data.profile.isActive ? "secondary" : "destructive"}>{data.profile.isActive ? "Active" : "Inactive"}</Badge>
                      <Badge variant="outline">{data.profile.publicId}</Badge>
                    </div>
                  </div>

                  <div className="space-y-4">
                    <div className="rounded-[1.25rem] border bg-slate-50/80 p-4">
                      <p className="text-xs font-semibold uppercase tracking-[0.2em] text-slate-500">Manual fallback token</p>
                      <p className="mt-3 break-all font-mono text-sm text-slate-900">{data.token}</p>
                      <Button variant="outline" className="mt-4" onClick={handleCopy}><Copy className="mr-2 h-4 w-4" /> Copy token</Button>
                    </div>
                    <div className="grid gap-4 md:grid-cols-2">
                      <div className="rounded-[1.25rem] border bg-white p-4">
                        <p className="text-sm text-slate-500">Issued</p>
                        <p className="mt-2 font-semibold text-slate-900">{formatDate(data.profile.issuedAt, "MMM dd, yyyy h:mm a")}</p>
                      </div>
                      <div className="rounded-[1.25rem] border bg-white p-4">
                        <p className="text-sm text-slate-500">Last used</p>
                        <p className="mt-2 font-semibold text-slate-900">{data.profile.lastUsedAt ? formatDate(data.profile.lastUsedAt, "MMM dd, yyyy h:mm a") : "Not used yet"}</p>
                      </div>
                    </div>
                    <div className="rounded-[1.25rem] border border-emerald-200 bg-emerald-50/70 p-4 text-sm text-emerald-900">
                      <div className="flex items-start gap-3">
                        <ShieldCheck className="mt-0.5 h-4 w-4" />
                        <p>Your QR token is protected server-side and your scan history is recorded for audit visibility.</p>
                      </div>
                    </div>
                  </div>
                </div>
              )}
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>Recent QR activity</CardTitle>
              <CardDescription>Your most recent QR attendance events appear here alongside direction and marking status.</CardDescription>
            </CardHeader>
            <CardContent className="p-0">
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead className="pl-6">Date</TableHead>
                    <TableHead>Direction</TableHead>
                    <TableHead>Status</TableHead>
                    <TableHead>Method</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {history.slice(0, 8).map((event: QrHistoryEvent) => (
                    <TableRow key={event.id}>
                      <TableCell className="pl-6 font-medium">{formatDate(event.scannedAt, "MMM dd, yyyy h:mm a")}</TableCell>
                      <TableCell>{event.direction}</TableCell>
                      <TableCell>{event.status ?? "—"}</TableCell>
                      <TableCell className="capitalize">{event.scanMethod}</TableCell>
                    </TableRow>
                  ))}
                  {history.length === 0 ? (
                    <TableRow><TableCell colSpan={4} className="py-10 text-center text-muted-foreground">No QR attendance events yet.</TableCell></TableRow>
                  ) : null}
                </TableBody>
              </Table>
            </CardContent>
          </Card>
        </div>
      </div>
    </Layout>
  );
}
