import { z } from "zod";

const optionalUrlSchema = z.union([z.string().trim().url("Enter a valid URL"), z.literal("")]).default("");
const optionalEmailSchema = z.union([z.string().trim().email("Enter a valid email"), z.literal("")]).default("");

export const schoolInformationSettingsSchema = z.object({
  schoolName: z.string().trim().min(2, "School name is required").default("School Nexus Academy"),
  shortName: z.string().trim().min(2, "Short name is required").max(24).default("School Nexus"),
  schoolCode: z.string().trim().min(2, "School code is required").max(16).default("SNA"),
  schoolEmail: optionalEmailSchema,
  schoolPhone: z.string().trim().max(30).default(""),
  schoolAddress: z.string().trim().max(250).default(""),
  websiteUrl: optionalUrlSchema,
  principalName: z.string().trim().max(80).default(""),
  motto: z.string().trim().max(120).default("Empowering every learner.")
});

export const academicConfigurationSettingsSchema = z.object({
  currentAcademicYear: z.string().trim().min(4).max(20).default("2025/2026"),
  currentTerm: z.string().trim().min(2).max(30).default("Term 1"),
  academicLevels: z.array(z.string().trim().min(1)).min(1).default(["Primary", "Secondary"]),
  gradingScale: z.array(z.string().trim().min(1)).min(1).default(["A", "B", "C", "D", "F"]),
  weekStartsOn: z.enum(["Monday", "Sunday", "Saturday"]).default("Monday"),
  periodsPerDay: z.number().int().min(1).max(12).default(8),
  passingScore: z.number().min(0).max(100).default(50)
});

export const financialSettingsSchema = z.object({
  currencyCode: z.string().trim().length(3, "Use a 3-letter currency code").default("USD"),
  currencySymbol: z.string().trim().min(1).max(4).default("$"),
  locale: z.string().trim().min(2).max(20).default("en-US"),
  timezone: z.string().trim().min(2).max(60).default("UTC"),
  dateFormat: z.enum(["PPP", "MMMM dd, yyyy", "dd/MM/yyyy", "MM/dd/yyyy", "yyyy-MM-dd"]).default("PPP"),
  invoicePrefix: z.string().trim().min(2).max(12).default("INV"),
  receiptPrefix: z.string().trim().min(2).max(12).default("RCT"),
  lateFeePercentage: z.number().min(0).max(100).default(0)
});

export const brandingSettingsSchema = z.object({
  primaryColor: z.string().trim().min(3).max(30).default("violet"),
  secondaryColor: z.string().trim().min(3).max(30).default("fuchsia"),
  accentColor: z.string().trim().min(3).max(30).default("pink"),
  logoUrl: optionalUrlSchema,
  faviconUrl: optionalUrlSchema,
  headerTitle: z.string().trim().min(2).max(80).default("School Nexus Dashboard"),
  headerSubtitle: z.string().trim().max(120).default("Connected school operations for modern teams"),
  loginWelcomeTitle: z.string().trim().min(2).max(80).default("Welcome back"),
  loginWelcomeSubtitle: z.string().trim().max(120).default("Sign in to continue into your school workspace")
});

export const systemPreferencesSettingsSchema = z.object({
  enablePublicBranding: z.boolean().default(true),
  enableDocumentWatermark: z.boolean().default(false),
  allowWeekendClasses: z.boolean().default(false),
  enableParentPortal: z.boolean().default(false),
  autoPromoteStudents: z.boolean().default(false),
  maintenanceMode: z.boolean().default(false),
  maintenanceMessage: z.string().trim().max(160).default("System maintenance is in progress. Please check back shortly.")
});

export const documentTemplatesSettingsSchema = z.object({
  invoiceHeader: z.string().trim().max(160).default("Official fee invoice"),
  reportCardHeader: z.string().trim().max(160).default("Academic performance report"),
  certificateHeader: z.string().trim().max(160).default("Certificate of achievement"),
  signatureLineLabel: z.string().trim().max(80).default("Authorized signature"),
  footerNote: z.string().trim().max(200).default("Generated by School Nexus"),
  reportCardFooter: z.string().trim().max(200).default("This report reflects the official school grading record."),
  certificateFooter: z.string().trim().max(200).default("This certificate is electronically generated and valid without a seal.")
});

export const notificationSettingsSchema = z.object({
  sendFeeReminders: z.boolean().default(true),
  sendAttendanceAlerts: z.boolean().default(true),
  sendResultPublishedAlerts: z.boolean().default(true),
  senderName: z.string().trim().max(80).default("School Nexus Notifications"),
  replyToEmail: optionalEmailSchema,
  smtpHost: z.string().trim().max(100).default(""),
  smtpPort: z.number().int().min(1).max(65535).default(587),
  smtpUsername: z.string().trim().max(120).default(""),
  smtpPassword: z.string().trim().max(200).default(""),
  smsApiKey: z.string().trim().max(200).default("")
});

export const schoolSettingsDataSchema = z.object({
  schoolInformation: schoolInformationSettingsSchema.default({}),
  academicConfiguration: academicConfigurationSettingsSchema.default({}),
  financialSettings: financialSettingsSchema.default({}),
  branding: brandingSettingsSchema.default({}),
  systemPreferences: systemPreferencesSettingsSchema.default({}),
  documentTemplates: documentTemplatesSettingsSchema.default({}),
  notificationSettings: notificationSettingsSchema.default({})
});

export const schoolSettingsCategoryKeySchema = z.enum([
  "schoolInformation",
  "academicConfiguration",
  "financialSettings",
  "branding",
  "systemPreferences",
  "documentTemplates",
  "notificationSettings"
]);

export const schoolSettingsAuditActionSchema = z.enum(["create", "update", "restore", "import"]);

export const schoolSettingsUserSummarySchema = z.object({
  id: z.number(),
  name: z.string(),
  email: z.string()
});

export const schoolSettingsCompletionItemSchema = z.object({
  key: z.string(),
  label: z.string(),
  category: schoolSettingsCategoryKeySchema,
  complete: z.boolean()
});

export const schoolSettingsRecordSchema = z.object({
  id: z.number(),
  version: z.number(),
  data: schoolSettingsDataSchema,
  createdAt: z.string(),
  updatedAt: z.string(),
  updatedBy: schoolSettingsUserSummarySchema.optional(),
  completionChecklist: z.array(schoolSettingsCompletionItemSchema),
  completionPercentage: z.number(),
  isSetupComplete: z.boolean()
});

export const schoolSettingsVersionSchema = z.object({
  id: z.number(),
  version: z.number(),
  changeSummary: z.string().nullable().optional(),
  createdAt: z.string(),
  createdBy: schoolSettingsUserSummarySchema.optional()
});

export const schoolSettingsAuditEntrySchema = z.object({
  id: z.number(),
  action: schoolSettingsAuditActionSchema,
  category: schoolSettingsCategoryKeySchema.optional(),
  fieldPath: z.string().optional(),
  previousValue: z.string().nullable().optional(),
  nextValue: z.string().nullable().optional(),
  changeSummary: z.string().nullable().optional(),
  createdAt: z.string(),
  createdBy: schoolSettingsUserSummarySchema.optional()
});

export const publicSchoolSettingsSchema = z.object({
  schoolInformation: schoolInformationSettingsSchema.pick({ schoolName: true, shortName: true, schoolEmail: true, schoolPhone: true, schoolAddress: true, websiteUrl: true, motto: true }),
  academicConfiguration: academicConfigurationSettingsSchema.pick({ currentAcademicYear: true, currentTerm: true, weekStartsOn: true }),
  financialSettings: financialSettingsSchema.pick({ locale: true, currencyCode: true, currencySymbol: true, timezone: true, dateFormat: true, invoicePrefix: true }),
  branding: brandingSettingsSchema,
  systemPreferences: systemPreferencesSettingsSchema.pick({ enablePublicBranding: true, enableDocumentWatermark: true, maintenanceMode: true, maintenanceMessage: true }),
  documentTemplates: documentTemplatesSettingsSchema.pick({ invoiceHeader: true, reportCardHeader: true, certificateHeader: true, signatureLineLabel: true, footerNote: true, reportCardFooter: true, certificateFooter: true }),
  setup: z.object({
    isComplete: z.boolean(),
    completionPercentage: z.number(),
    checklist: z.array(schoolSettingsCompletionItemSchema)
  })
});

export const adminSchoolSettingsResponseSchema = z.object({
  settings: schoolSettingsRecordSchema,
  publicSettings: publicSchoolSettingsSchema,
  versions: z.array(schoolSettingsVersionSchema),
  auditLog: z.array(schoolSettingsAuditEntrySchema)
});

export const updateSchoolSettingsInputSchema = z.object({
  data: schoolSettingsDataSchema,
  changeSummary: z.string().trim().max(180).optional()
});

export const restoreSchoolSettingsInputSchema = z.object({
  version: z.number().int().positive(),
  changeSummary: z.string().trim().max(180).optional()
});

export const exportSchoolSettingsResponseSchema = z.object({
  exportedAt: z.string(),
  version: z.number(),
  data: schoolSettingsDataSchema
});

export const schoolSettingsCategoryLabels: Record<SchoolSettingsCategoryKey, string> = {
  schoolInformation: "School Information",
  academicConfiguration: "Academic Configuration",
  financialSettings: "Financial Settings",
  branding: "Branding & Appearance",
  systemPreferences: "System Preferences",
  documentTemplates: "Document Templates",
  notificationSettings: "Notification Settings"
};

export type SchoolSettingsData = z.infer<typeof schoolSettingsDataSchema>;
export type SchoolSettingsCategoryKey = z.infer<typeof schoolSettingsCategoryKeySchema>;
export type SchoolSettingsAuditAction = z.infer<typeof schoolSettingsAuditActionSchema>;
export type SchoolSettingsCompletionItem = z.infer<typeof schoolSettingsCompletionItemSchema>;
export type PublicSchoolSettings = z.infer<typeof publicSchoolSettingsSchema>;
export type AdminSchoolSettingsResponse = z.infer<typeof adminSchoolSettingsResponseSchema>;

export const defaultSchoolSettingsData = schoolSettingsDataSchema.parse({});

export function cloneSchoolSettingsData(data: SchoolSettingsData) {
  return schoolSettingsDataSchema.parse(JSON.parse(JSON.stringify(data)));
}